import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Terminal, Github, FileText, Sparkles, ArrowRight, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";

const STORAGE_KEY = "specforge-onboarding-done";

const STEPS = [
  {
    icon: Terminal,
    iconColor: "hsl(263,90%,70%)",
    iconBg: "rgba(139,92,246,0.15)",
    iconBorder: "rgba(139,92,246,0.3)",
    title: "Welcome to SpecForge",
    subtitle: "AI-powered technical spec generation",
    body: "Turn any GitHub repo or plain description into a production-ready technical specification in seconds. System designs, API blueprints, database schemas — all generated by AI.",
    cta: "How it works →",
  },
  {
    icon: Github,
    iconColor: "#06B6D4",
    iconBg: "rgba(6,182,212,0.15)",
    iconBorder: "rgba(6,182,212,0.3)",
    title: "Paste a GitHub URL or describe your project",
    subtitle: "Two input modes",
    body: "Point SpecForge at a GitHub repository and it reads the actual code. Or just describe what you want to build in plain English — no code needed.",
    cta: "Got it →",
  },
  {
    icon: Sparkles,
    iconColor: "#10B981",
    iconBg: "rgba(16,185,129,0.15)",
    iconBorder: "rgba(16,185,129,0.3)",
    title: "Your spec is ready in under 30 seconds",
    subtitle: "What you get",
    body: "A structured document with architecture decisions, data models, API endpoints, security considerations, and a Mermaid diagram. Export to PDF, Markdown, or Word.",
    cta: "Generate my first spec",
  },
];

interface Props {
  onDismiss: () => void;
}

export function OnboardingOverlay({ onDismiss }: Props) {
  const [step, setStep] = useState(0);
  const current = STEPS[step];
  const Icon = current.icon;
  const isLast = step === STEPS.length - 1;

  const handleNext = () => {
    if (isLast) {
      onDismiss();
    } else {
      setStep(s => s + 1);
    }
  };

  return (
    <motion.div
      className="fixed inset-0 z-[9999] flex items-center justify-center p-4"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <motion.div
        className="absolute inset-0 bg-black/70 backdrop-blur-md"
        onClick={onDismiss}
      />

      <motion.div
        className="relative w-full max-w-md rounded-2xl overflow-hidden"
        style={{
          background: "rgba(10,10,18,0.98)",
          border: "1px solid rgba(139,92,246,0.3)",
          boxShadow: "0 0 80px rgba(139,92,246,0.2), 0 32px 64px rgba(0,0,0,0.7)",
        }}
        initial={{ opacity: 0, scale: 0.92, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        transition={{ type: "spring", stiffness: 360, damping: 30 }}
      >
        {/* Close */}
        <button
          onClick={onDismiss}
          className="absolute top-4 right-4 p-1.5 rounded-md text-muted-foreground hover:text-foreground transition-colors z-10"
          style={{ border: "1px solid rgba(255,255,255,0.06)" }}
        >
          <X className="w-3.5 h-3.5" />
        </button>

        {/* Step dots */}
        <div className="absolute top-4 left-1/2 -translate-x-1/2 flex items-center gap-1.5">
          {STEPS.map((_, i) => (
            <div
              key={i}
              className="rounded-full transition-all duration-300"
              style={{
                width: i === step ? "20px" : "6px",
                height: "6px",
                background: i === step
                  ? "hsl(263,90%,70%)"
                  : "rgba(255,255,255,0.15)",
              }}
            />
          ))}
        </div>

        <AnimatePresence mode="wait">
          <motion.div
            key={step}
            className="p-8 pt-14"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.2 }}
          >
            {/* Icon */}
            <div className="flex justify-center mb-6">
              <div className="relative">
                <div
                  className="w-16 h-16 rounded-2xl flex items-center justify-center"
                  style={{
                    background: current.iconBg,
                    border: `1px solid ${current.iconBorder}`,
                  }}
                >
                  <Icon className="w-7 h-7" style={{ color: current.iconColor }} />
                </div>
                <div
                  className="absolute -inset-4 rounded-3xl opacity-20 blur-2xl pointer-events-none"
                  style={{ background: `radial-gradient(circle, ${current.iconColor}, transparent)` }}
                />
              </div>
            </div>

            {/* Text */}
            <div className="text-center space-y-2 mb-6">
              <p className="text-[10px] font-mono text-muted-foreground uppercase tracking-widest">
                {current.subtitle}
              </p>
              <h2 className="text-lg font-bold text-white leading-snug">
                {current.title}
              </h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {current.body}
              </p>
            </div>

            {/* CTA */}
            <Button
              className="w-full font-mono text-sm h-11"
              onClick={handleNext}
              style={{
                background: isLast
                  ? "linear-gradient(135deg, hsl(263,90%,60%), hsl(193,90%,50%))"
                  : undefined,
              }}
            >
              {isLast && <Zap className="w-4 h-4 mr-2" />}
              {current.cta}
              {!isLast && <ArrowRight className="w-4 h-4 ml-2" />}
            </Button>

            {/* Skip */}
            {!isLast && (
              <button
                onClick={onDismiss}
                className="w-full mt-3 text-[10px] font-mono text-muted-foreground/50 hover:text-muted-foreground transition-colors"
              >
                Skip intro
              </button>
            )}
          </motion.div>
        </AnimatePresence>
      </motion.div>
    </motion.div>
  );
}

export function useOnboarding(hasSpecs: boolean) {
  const [show, setShow] = useState(false);

  useEffect(() => {
    const done = localStorage.getItem(STORAGE_KEY);
    if (!done && !hasSpecs) {
      const t = setTimeout(() => setShow(true), 800);
      return () => clearTimeout(t);
    }
    return undefined;
  }, [hasSpecs]);

  const dismiss = () => {
    localStorage.setItem(STORAGE_KEY, "1");
    setShow(false);
  };

  return { show, dismiss };
}
