import { Router, type IRouter } from "express";
import healthRouter from "./health";
import specsRouter from "./specs";
import anthropicRouter from "./anthropic";
import authRouter from "./auth";
import webhooksRouter from "./webhooks";
import presenceRouter from "./presence";
import insightsRouter from "./insights";
import notificationsRouter from "./notifications";
import versionsRouter from "./versions";
import exportRouter from "./export";
import teamsRouter from "./teams";
import preferencesRouter from "./preferences";
import mcpRouter from "./mcp";
import shareRouter from "./share";
import githubSyncRouter from "./github-sync";
import searchRouter from "./search";
import specDependenciesRouter from "./spec-dependencies";
import teamKnowledgeRouter from "./team-knowledge";
import auditLogsRouter from "./audit-logs";
import ssoRouter from "./sso";
import prAgentRouter from "./pr-agent";
import specConflictsRouter from "./spec-conflicts";
import specHealthRouter from "./spec-health";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use("/specs", specsRouter);
router.use("/specs", versionsRouter);
router.use("/specs", exportRouter);
router.use("/specs", shareRouter);
router.use("/specs", githubSyncRouter);
router.use("/specs", specDependenciesRouter);
router.use(searchRouter);
router.use("/teams", teamsRouter);
router.use("/teams", teamKnowledgeRouter);
router.use("/teams", auditLogsRouter);
router.use(ssoRouter);
router.use("/specs", prAgentRouter);
router.use("/specs", specHealthRouter);
router.use("/teams", specConflictsRouter);
router.use("/anthropic", anthropicRouter);
router.use(webhooksRouter);
router.use(presenceRouter);
router.use(insightsRouter);
router.use(notificationsRouter);
router.use(preferencesRouter);
router.use("/mcp", mcpRouter);

export default router;
