import { useState, useEffect } from "react";
import { useParams, Link } from "wouter";
import { motion } from "framer-motion";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { MermaidDiagram } from "@/components/mermaid-diagram";
import { ComplexityScoreCard } from "@/components/complexity-score-card";
import {
  FileCode2,
  Network,
  ArrowLeft,
  Copy,
  Download,
  Clock,
  Github,
  FileText,
  Eye,
  Server,
  Cpu,
  Database,
  BookOpen,
  Terminal,
} from "lucide-react";
import { SpecForgeLogo } from "@/components/spec-forge-logo";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { format } from "date-fns";

type Spec = {
  id: number;
  title: string;
  specType: string;
  inputType: string;
  inputValue: string;
  content: string;
  status: string;
  complexityScore: number | null;
  techDebtRisks: any[] | null;
  complexitySummary: string | null;
  mermaidDiagram: string | null;
  shareToken: string | null;
  viewCount: number;
  createdAt: string;
  updatedAt: string;
};

function getSpecTypeLabel(type: string) {
  const map: Record<string, string> = {
    system_design: "System Design",
    api_design: "API Design",
    database_schema: "Database Schema",
    feature_spec: "Feature Spec",
  };
  return map[type] ?? type;
}

function getSpecTypeIcon(type: string) {
  switch (type) {
    case "system_design": return <Server className="w-3 h-3" />;
    case "api_design": return <Cpu className="w-3 h-3" />;
    case "database_schema": return <Database className="w-3 h-3" />;
    case "feature_spec": return <BookOpen className="w-3 h-3" />;
    default: return <FileText className="w-3 h-3" />;
  }
}

export default function SharedSpec() {
  const { token } = useParams();
  const { toast } = useToast();
  const [spec, setSpec] = useState<Spec | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(false);
  const [activeTab, setActiveTab] = useState<"document" | "diagram">("document");

  useEffect(() => {
    async function fetchSpec() {
      try {
        const res = await fetch(`/api/specs/share/${token}`);
        if (!res.ok) throw new Error("Not found");
        const data = await res.json();
        setSpec(data);
      } catch {
        setError(true);
      } finally {
        setIsLoading(false);
      }
    }
    if (token) fetchSpec();
  }, [token]);

  const handleCopy = () => {
    if (spec?.content) {
      navigator.clipboard.writeText(spec.content);
      toast({ title: "Copied to clipboard" });
    }
  };

  const handleDownload = () => {
    if (spec?.content) {
      const blob = new Blob([spec.content], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${spec.title.toLowerCase().replace(/\s+/g, "-")}-spec.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="flex flex-col items-center gap-4 text-muted-foreground">
          <Terminal className="w-8 h-8 opacity-20 animate-pulse" />
          <span className="font-mono text-sm">Loading shared spec...</span>
        </div>
      </div>
    );
  }

  if (error || !spec) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center space-y-4">
          <h2 className="text-xl font-bold text-destructive font-mono">LINK_EXPIRED_OR_INVALID</h2>
          <p className="text-muted-foreground text-sm">This shared spec could not be found.</p>
          <Link href="/">
            <Button variant="outline" className="font-mono">
              <ArrowLeft className="w-4 h-4 mr-2" /> Back to SpecForge
            </Button>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Print-only header */}
      <div className="print-show hidden print-header">
        <div className="text-2xl font-bold">{spec.title}</div>
        <div className="text-sm text-gray-600 mt-1">
          {getSpecTypeLabel(spec.specType)} · {format(new Date(spec.createdAt), "MMMM d, yyyy")} · {spec.viewCount} views
        </div>
        <div className="text-xs text-gray-500 mt-1">Generated by SpecForge</div>
      </div>

      {/* Navbar */}
      <nav className="print-hide sticky top-0 z-50 border-b border-border bg-background/80 backdrop-blur-xl">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/">
            <div className="flex items-center gap-2 cursor-pointer">
              <SpecForgeLogo size={28} textSize="text-sm" />
              <span className="text-xs font-mono text-muted-foreground ml-1 border border-border px-2 py-0.5 rounded">Shared</span>
            </div>
          </Link>
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-1.5 text-xs font-mono text-muted-foreground border border-border px-3 py-1.5 rounded-md">
              <Eye className="w-3.5 h-3.5" />
              {spec.viewCount} views
            </div>
            <Button variant="outline" size="sm" onClick={handleCopy} className="font-mono text-xs">
              <Copy className="w-3 h-3 mr-2" /> Copy MD
            </Button>
            <Button variant="outline" size="sm" onClick={handlePrint} className="font-mono text-xs">
              <Download className="w-3 h-3 mr-2" /> Export PDF
            </Button>
            <Link href="/app">
              <Button size="sm" className="font-mono text-xs">
                Generate Yours →
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      <div className="max-w-6xl mx-auto px-6 py-8">
        {/* Spec Header */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-6 print-hide"
        >
          <div className="flex items-start justify-between gap-4">
            <div>
              <h1 className="text-2xl font-bold mb-2">{spec.title}</h1>
              <div className="flex items-center gap-3 text-xs text-muted-foreground font-mono">
                <span className="flex items-center gap-1">
                  {spec.inputType === "github_url" ? <Github className="w-3 h-3" /> : <FileText className="w-3 h-3" />}
                  {spec.inputType === "github_url" ? "GitHub" : "Description"}
                </span>
                <span>·</span>
                <span className="flex items-center gap-1">
                  <Clock className="w-3 h-3" />
                  {format(new Date(spec.createdAt), "MMM d, yyyy HH:mm")}
                </span>
              </div>
            </div>
            <Badge variant="outline" className="bg-primary/10 text-primary border-primary/20 gap-1.5 py-1 px-2.5 shrink-0">
              {getSpecTypeIcon(spec.specType)}
              {getSpecTypeLabel(spec.specType)}
            </Badge>
          </div>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Main content */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="lg:col-span-3"
          >
            <div className="rounded-xl border border-border bg-[#0a0a0a] overflow-hidden">
              {/* Tabs */}
              <div className="print-hide border-b border-border bg-card flex">
                <button
                  onClick={() => setActiveTab("document")}
                  className={`px-4 py-3 text-sm font-mono flex items-center gap-2 border-b-2 transition-colors ${activeTab === "document" ? "border-primary text-foreground" : "border-transparent text-muted-foreground hover:text-foreground"}`}
                >
                  <FileCode2 className="w-4 h-4" /> Document
                </button>
                {spec.mermaidDiagram && (
                  <button
                    onClick={() => setActiveTab("diagram")}
                    className={`px-4 py-3 text-sm font-mono flex items-center gap-2 border-b-2 transition-colors ${activeTab === "diagram" ? "border-primary text-foreground" : "border-transparent text-muted-foreground hover:text-foreground"}`}
                  >
                    <Network className="w-4 h-4" /> Diagram
                  </button>
                )}
              </div>

              {/* Content */}
              <div className="print-content">
                {activeTab === "document" ? (
                  <div className="p-8 prose prose-invert max-w-none prose-pre:bg-black/50 prose-pre:border prose-pre:border-border">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>
                      {spec.content}
                    </ReactMarkdown>
                  </div>
                ) : spec.mermaidDiagram ? (
                  <div className="p-8 min-h-[500px] h-[600px]">
                    <MermaidDiagram chart={spec.mermaidDiagram} />
                  </div>
                ) : null}
              </div>
            </div>
          </motion.div>

          {/* Sidebar */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="lg:col-span-1 space-y-4 print-hide"
          >
            <ComplexityScoreCard
              score={spec.complexityScore ?? null}
              label={null}
              risks={spec.techDebtRisks as any ?? null}
              summary={spec.complexitySummary ?? null}
            />

            {/* CTA card */}
            <div className="rounded-xl border border-border bg-card p-5 space-y-3">
              <p className="text-xs font-mono text-muted-foreground">Generate your own spec with SpecForge — free, no signup.</p>
              <Link href="/app">
                <Button className="w-full font-mono text-xs">
                  <Terminal className="w-3.5 h-3.5 mr-2" />
                  Try SpecForge Free
                </Button>
              </Link>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
